#!/bin/bash
# activate.sh
BONSAI_ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
export BONSAI_EXE_PATH="$BONSAI_ENV_DIR/Bonsai.exe"
export ORIGINAL_PS1="$PS1"
export PS1="($(basename $BONSAI_ENV_DIR)) $PS1"
export NUGET_CONFIG="$BONSAI_ENV_DIR/NuGet.config"
alias bonsai='mono "$BONSAI_EXE_PATH"'
alias bonsai-clean='GTK_DATA_PREFIX= mono "$BONSAI_EXE_PATH"'
alias deactivate='source $BONSAI_ENV_DIR/deactivate'
echo "Activated bonsai environment in $BONSAI_ENV_DIR"