//----------------------
// <auto-generated>
//     Generated using the NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0) (http://NJsonSchema.org)
// </auto-generated>
//----------------------


namespace DataSchema
{
    #pragma warning disable // Disable all warnings

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.4.1.0")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class Session
    {
    
        private int _id;
    
        private string _name;
    
        private Trial _trial = new Trial();
    
        public Session()
        {
        }
    
        protected Session(Session other)
        {
            _id = other._id;
            _name = other._name;
            _trial = other._trial;
        }
    
        public int Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public Trial Trial
        {
            get
            {
                return _trial;
            }
            set
            {
                _trial = value;
            }
        }
    
        public System.IObservable<Session> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Session(this)));
        }
    
        public System.IObservable<Session> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Session(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("id = " + _id + ", ");
            stringBuilder.Append("name = " + _name + ", ");
            stringBuilder.Append("trial = " + _trial);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.4.1.0")]
    [Bonsai.CombinatorAttribute()]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Source)]
    public partial class Trial
    {
    
        private int _id;
    
        private string _name;
    
        public Trial()
        {
        }
    
        protected Trial(Trial other)
        {
            _id = other._id;
            _name = other._name;
        }
    
        public int Id
        {
            get
            {
                return _id;
            }
            set
            {
                _id = value;
            }
        }
    
        public string Name
        {
            get
            {
                return _name;
            }
            set
            {
                _name = value;
            }
        }
    
        public System.IObservable<Trial> Process()
        {
            return System.Reactive.Linq.Observable.Defer(() => System.Reactive.Linq.Observable.Return(new Trial(this)));
        }
    
        public System.IObservable<Trial> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Select(source, _ => new Trial(this));
        }
    
        protected virtual bool PrintMembers(System.Text.StringBuilder stringBuilder)
        {
            stringBuilder.Append("id = " + _id + ", ");
            stringBuilder.Append("name = " + _name);
            return true;
        }
    
        public override string ToString()
        {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append(GetType().Name);
            stringBuilder.Append(" { ");
            if (PrintMembers(stringBuilder))
            {
                stringBuilder.Append(" ");
            }
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
    }


    /// <summary>
    /// Provides a collection of methods for converting generic Python objects into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.4.1.0")]
    [System.ComponentModel.DescriptionAttribute("Provides a collection of methods for converting generic Python objects into data " +
        "model objects.")]
    public partial class PyObjectConverter : Bonsai.Sink, Python.Runtime.IPyObjectDecoder
    {
    
        static readonly System.Collections.Generic.Dictionary<System.Type, System.Func<Python.Runtime.PyObject, object>> decoders =
            new System.Collections.Generic.Dictionary<System.Type, System.Func<Python.Runtime.PyObject, object>>
            {
                { typeof(Session), CreateDecoder<Session>(DecodeSession) },
                { typeof(Trial), CreateDecoder<Trial>(DecodeTrial) }
            };

        private static T GetAttr<T>(Python.Runtime.PyObject pyObj, string attributeName)
        {
            using (var attr = pyObj.GetAttr(attributeName))
            {
                return attr.As<T>();
            }
        }

        static System.Func<Python.Runtime.PyObject, object> CreateDecoder<T>(System.Action<Python.Runtime.PyObject, T> decode)
            where T : new()
        {
            return pyObj =>
            {
                T value = new T();
                decode(pyObj, value);
                return value;
            };
        }

        public bool CanDecode(Python.Runtime.PyType objectType, System.Type targetType)
        {
            return decoders.ContainsKey(targetType);
        }

        public bool TryDecode<T>(Python.Runtime.PyObject pyObj, out T value)
        {
            System.Func<Python.Runtime.PyObject, object> decoder;
            if (decoders.TryGetValue(typeof(T), out decoder))
            {
                value = (T)decoder(pyObj);
                return true;
            }
            value = default(T);
            return false;
        }
        public override System.IObservable<TSource> Process<TSource>(System.IObservable<TSource> source)
        {
            return System.Reactive.Linq.Observable.Do(source, _ => Python.Runtime.PyObjectConversions.RegisterDecoder(this));
        }
    
        static void DecodeSession(Python.Runtime.PyObject pyObj, Session value)
        {
            value.Id = GetAttr<int>(pyObj, "id");
            value.Name = GetAttr<string>(pyObj, "name");
            value.Trial = GetAttr<Trial>(pyObj, "trial");
        }
    
        static void DecodeTrial(Python.Runtime.PyObject pyObj, Trial value)
        {
            value.Id = GetAttr<int>(pyObj, "id");
            value.Name = GetAttr<string>(pyObj, "name");
        }
    }


    /// <summary>
    /// Converts a sequence of generic Python objects into data model objects.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Bonsai.Sgen", "0.4.1.0")]
    [System.ComponentModel.DescriptionAttribute("Converts a sequence of generic Python objects into data model objects.")]
    [System.ComponentModel.DefaultPropertyAttribute("Type")]
    [Bonsai.WorkflowElementCategoryAttribute(Bonsai.ElementCategory.Transform)]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Session>))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Bonsai.Expressions.TypeMapping<Trial>))]
    public partial class FromPython : Bonsai.Expressions.SingleArgumentExpressionBuilder
    {
    
        public FromPython()
        {
            Type = new Bonsai.Expressions.TypeMapping<Session>();
        }

        public Bonsai.Expressions.TypeMapping Type { get; set; }

        public override System.Linq.Expressions.Expression Build(System.Collections.Generic.IEnumerable<System.Linq.Expressions.Expression> arguments)
        {
            var typeMapping = (Bonsai.Expressions.TypeMapping)Type;
            var returnType = typeMapping.GetType().GetGenericArguments()[0];
            return System.Linq.Expressions.Expression.Call(
                typeof(FromPython),
                "Process",
                new System.Type[] { returnType },
                System.Linq.Enumerable.Single(arguments));
        }

        private static System.IObservable<T> Process<T>(System.IObservable<Python.Runtime.PyObject> source)
        {
            return System.Reactive.Linq.Observable.Select(source, value => value.As<T>());
        }
    }
}